// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CustomerFeedback.proto

package CustomerFeedback

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PassengerFeedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerFeedback) Reset()         { *m = PassengerFeedback{} }
func (m *PassengerFeedback) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedback) ProtoMessage()    {}
func (*PassengerFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52d2cf1795affa, []int{0}
}

func (m *PassengerFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedback.Unmarshal(m, b)
}
func (m *PassengerFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedback.Marshal(b, m, deterministic)
}
func (m *PassengerFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedback.Merge(m, src)
}
func (m *PassengerFeedback) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedback.Size(m)
}
func (m *PassengerFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedback proto.InternalMessageInfo

func (m *PassengerFeedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedback) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

func (m *PassengerFeedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type AddFeedbackRequest struct {
	PassengerFeedback    *PassengerFeedback `protobuf:"bytes,1,opt,name=passengerFeedback,proto3" json:"passengerFeedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AddFeedbackRequest) Reset()         { *m = AddFeedbackRequest{} }
func (m *AddFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*AddFeedbackRequest) ProtoMessage()    {}
func (*AddFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52d2cf1795affa, []int{1}
}

func (m *AddFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeedbackRequest.Unmarshal(m, b)
}
func (m *AddFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *AddFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeedbackRequest.Merge(m, src)
}
func (m *AddFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_AddFeedbackRequest.Size(m)
}
func (m *AddFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeedbackRequest proto.InternalMessageInfo

func (m *AddFeedbackRequest) GetPassengerFeedback() *PassengerFeedback {
	if m != nil {
		return m.PassengerFeedback
	}
	return nil
}

type AddFeedbackResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeedbackResponse) Reset()         { *m = AddFeedbackResponse{} }
func (m *AddFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*AddFeedbackResponse) ProtoMessage()    {}
func (*AddFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52d2cf1795affa, []int{2}
}

func (m *AddFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeedbackResponse.Unmarshal(m, b)
}
func (m *AddFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *AddFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeedbackResponse.Merge(m, src)
}
func (m *AddFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_AddFeedbackResponse.Size(m)
}
func (m *AddFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeedbackResponse proto.InternalMessageInfo

func (m *AddFeedbackResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetFeedbackByPassengerIDRequest struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedbackByPassengerIDRequest) Reset()         { *m = GetFeedbackByPassengerIDRequest{} }
func (m *GetFeedbackByPassengerIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByPassengerIDRequest) ProtoMessage()    {}
func (*GetFeedbackByPassengerIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52d2cf1795affa, []int{3}
}

func (m *GetFeedbackByPassengerIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByPassengerIDRequest.Unmarshal(m, b)
}
func (m *GetFeedbackByPassengerIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByPassengerIDRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedbackByPassengerIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByPassengerIDRequest.Merge(m, src)
}
func (m *GetFeedbackByPassengerIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByPassengerIDRequest.Size(m)
}
func (m *GetFeedbackByPassengerIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByPassengerIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByPassengerIDRequest proto.InternalMessageInfo

func (m *GetFeedbackByPassengerIDRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type GetFeedbackByPassengerIDResponse struct {
	Feedbacks            []*PassengerFeedback `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetFeedbackByPassengerIDResponse) Reset()         { *m = GetFeedbackByPassengerIDResponse{} }
func (m *GetFeedbackByPassengerIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByPassengerIDResponse) ProtoMessage()    {}
func (*GetFeedbackByPassengerIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52d2cf1795affa, []int{4}
}

func (m *GetFeedbackByPassengerIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByPassengerIDResponse.Unmarshal(m, b)
}
func (m *GetFeedbackByPassengerIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByPassengerIDResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedbackByPassengerIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByPassengerIDResponse.Merge(m, src)
}
func (m *GetFeedbackByPassengerIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByPassengerIDResponse.Size(m)
}
func (m *GetFeedbackByPassengerIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByPassengerIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByPassengerIDResponse proto.InternalMessageInfo

func (m *GetFeedbackByPassengerIDResponse) GetFeedbacks() []*PassengerFeedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

type GetFeedbackByBookingCodeRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedbackByBookingCodeRequest) Reset()         { *m = GetFeedbackByBookingCodeRequest{} }
func (m *GetFeedbackByBookingCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByBookingCodeRequest) ProtoMessage()    {}
func (*GetFeedbackByBookingCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52d2cf1795affa, []int{5}
}

func (m *GetFeedbackByBookingCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByBookingCodeRequest.Unmarshal(m, b)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByBookingCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByBookingCodeRequest.Merge(m, src)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByBookingCodeRequest.Size(m)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByBookingCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByBookingCodeRequest proto.InternalMessageInfo

func (m *GetFeedbackByBookingCodeRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type GetFeedbackByBookingCodeResponse struct {
	PassengerFeedback    *PassengerFeedback `protobuf:"bytes,1,opt,name=passengerFeedback,proto3" json:"passengerFeedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetFeedbackByBookingCodeResponse) Reset()         { *m = GetFeedbackByBookingCodeResponse{} }
func (m *GetFeedbackByBookingCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByBookingCodeResponse) ProtoMessage()    {}
func (*GetFeedbackByBookingCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52d2cf1795affa, []int{6}
}

func (m *GetFeedbackByBookingCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByBookingCodeResponse.Unmarshal(m, b)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByBookingCodeResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByBookingCodeResponse.Merge(m, src)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByBookingCodeResponse.Size(m)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByBookingCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByBookingCodeResponse proto.InternalMessageInfo

func (m *GetFeedbackByBookingCodeResponse) GetPassengerFeedback() *PassengerFeedback {
	if m != nil {
		return m.PassengerFeedback
	}
	return nil
}

func init() {
	proto.RegisterType((*PassengerFeedback)(nil), "CustomerFeedback.PassengerFeedback")
	proto.RegisterType((*AddFeedbackRequest)(nil), "CustomerFeedback.AddFeedbackRequest")
	proto.RegisterType((*AddFeedbackResponse)(nil), "CustomerFeedback.AddFeedbackResponse")
	proto.RegisterType((*GetFeedbackByPassengerIDRequest)(nil), "CustomerFeedback.GetFeedbackByPassengerIDRequest")
	proto.RegisterType((*GetFeedbackByPassengerIDResponse)(nil), "CustomerFeedback.GetFeedbackByPassengerIDResponse")
	proto.RegisterType((*GetFeedbackByBookingCodeRequest)(nil), "CustomerFeedback.GetFeedbackByBookingCodeRequest")
	proto.RegisterType((*GetFeedbackByBookingCodeResponse)(nil), "CustomerFeedback.GetFeedbackByBookingCodeResponse")
}

func init() { proto.RegisterFile("CustomerFeedback.proto", fileDescriptor_5c52d2cf1795affa) }

var fileDescriptor_5c52d2cf1795affa = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xbb, 0x25, 0xff, 0x7f, 0xec, 0x70, 0x69, 0xc7, 0xc4, 0x10, 0x2e, 0x92, 0x55, 0x63,
	0x4f, 0x4d, 0xc4, 0x4f, 0xd0, 0x62, 0x34, 0xde, 0x2a, 0x67, 0x2f, 0x45, 0x46, 0x62, 0x9a, 0xb2,
	0xd8, 0x85, 0x83, 0x67, 0xbf, 0xb6, 0x07, 0x53, 0x04, 0xd9, 0x32, 0x22, 0x9a, 0x78, 0x6b, 0x27,
	0x33, 0x6f, 0x7e, 0x6f, 0xdf, 0x04, 0x38, 0x0a, 0x0a, 0x9d, 0xab, 0x0d, 0x6d, 0xaf, 0x89, 0xe2,
	0x68, 0xf5, 0xb0, 0x9e, 0x65, 0x5b, 0x95, 0x2b, 0x1c, 0xb7, 0xeb, 0x52, 0xc3, 0x64, 0xb9, 0xd2,
	0x9a, 0xd2, 0xa4, 0x29, 0xa2, 0x07, 0x76, 0xa4, 0xd4, 0xfa, 0x29, 0x4d, 0x02, 0x15, 0x93, 0x23,
	0x3c, 0x31, 0x1d, 0x85, 0x66, 0x69, 0xd7, 0x91, 0xd5, 0x63, 0xb7, 0x57, 0xce, 0xd0, 0x13, 0xd3,
	0x7f, 0xa1, 0x59, 0x42, 0x17, 0x0e, 0x1e, 0x2b, 0x3d, 0xc7, 0x2a, 0x05, 0x3e, 0xff, 0xcb, 0x04,
	0x70, 0x1e, 0xc7, 0xf5, 0xba, 0x90, 0x9e, 0x0b, 0xd2, 0x39, 0xde, 0xc1, 0x24, 0x6b, 0xa3, 0x94,
	0xbb, 0x6d, 0xff, 0x64, 0xc6, 0x0c, 0x31, 0xea, 0x90, 0x4f, 0xcb, 0x73, 0x38, 0xdc, 0x5b, 0xa4,
	0x33, 0x95, 0x6a, 0xc2, 0x31, 0x58, 0x1b, 0x9d, 0x54, 0xbe, 0x76, 0x3f, 0x65, 0x00, 0xc7, 0x37,
	0x94, 0xd7, 0x8d, 0x8b, 0x97, 0x65, 0xe3, 0xa4, 0xc6, 0x6b, 0x59, 0x16, 0xcc, 0xb2, 0x24, 0xf0,
	0xba, 0x45, 0xaa, 0xd5, 0x73, 0x18, 0xd5, 0xcf, 0xa0, 0x1d, 0xe1, 0x59, 0x3f, 0x35, 0xd7, 0x4c,
	0x31, 0xd6, 0x45, 0x93, 0x8b, 0xc1, 0xfa, 0x7d, 0x80, 0xb2, 0x68, 0xb1, 0xee, 0x89, 0x54, 0xac,
	0x7f, 0x1f, 0x88, 0xff, 0x36, 0x04, 0x76, 0x83, 0x78, 0x0f, 0xb6, 0x91, 0x12, 0x9e, 0x72, 0x6d,
	0x7e, 0x2d, 0xee, 0x59, 0x4f, 0xd7, 0x87, 0x07, 0x39, 0xc0, 0x57, 0x01, 0x4e, 0x57, 0x2c, 0x78,
	0xc1, 0x55, 0x7a, 0xee, 0xc0, 0xf5, 0x7f, 0x33, 0xd2, 0x4d, 0x61, 0x3c, 0x78, 0x2f, 0x05, 0x4f,
	0xb8, 0x97, 0xe2, 0x8b, 0x3c, 0xe5, 0x20, 0xfa, 0x5f, 0x7e, 0x06, 0x2e, 0xdf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x89, 0xbf, 0x10, 0x00, 0x20, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerFeedbackClient is the client API for CustomerFeedback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerFeedbackClient interface {
	AddFeedback(ctx context.Context, in *AddFeedbackRequest, opts ...grpc.CallOption) (*AddFeedbackResponse, error)
	GetFeedbackByPassengerID(ctx context.Context, in *GetFeedbackByPassengerIDRequest, opts ...grpc.CallOption) (*GetFeedbackByPassengerIDResponse, error)
	GetFeedbackByBookingCode(ctx context.Context, in *GetFeedbackByBookingCodeRequest, opts ...grpc.CallOption) (*GetFeedbackByBookingCodeResponse, error)
}

type customerFeedbackClient struct {
	cc *grpc.ClientConn
}

func NewCustomerFeedbackClient(cc *grpc.ClientConn) CustomerFeedbackClient {
	return &customerFeedbackClient{cc}
}

func (c *customerFeedbackClient) AddFeedback(ctx context.Context, in *AddFeedbackRequest, opts ...grpc.CallOption) (*AddFeedbackResponse, error) {
	out := new(AddFeedbackResponse)
	err := c.cc.Invoke(ctx, "/CustomerFeedback.CustomerFeedback/AddFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerFeedbackClient) GetFeedbackByPassengerID(ctx context.Context, in *GetFeedbackByPassengerIDRequest, opts ...grpc.CallOption) (*GetFeedbackByPassengerIDResponse, error) {
	out := new(GetFeedbackByPassengerIDResponse)
	err := c.cc.Invoke(ctx, "/CustomerFeedback.CustomerFeedback/GetFeedbackByPassengerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerFeedbackClient) GetFeedbackByBookingCode(ctx context.Context, in *GetFeedbackByBookingCodeRequest, opts ...grpc.CallOption) (*GetFeedbackByBookingCodeResponse, error) {
	out := new(GetFeedbackByBookingCodeResponse)
	err := c.cc.Invoke(ctx, "/CustomerFeedback.CustomerFeedback/GetFeedbackByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerFeedbackServer is the server API for CustomerFeedback service.
type CustomerFeedbackServer interface {
	AddFeedback(context.Context, *AddFeedbackRequest) (*AddFeedbackResponse, error)
	GetFeedbackByPassengerID(context.Context, *GetFeedbackByPassengerIDRequest) (*GetFeedbackByPassengerIDResponse, error)
	GetFeedbackByBookingCode(context.Context, *GetFeedbackByBookingCodeRequest) (*GetFeedbackByBookingCodeResponse, error)
}

// UnimplementedCustomerFeedbackServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerFeedbackServer struct {
}

func (*UnimplementedCustomerFeedbackServer) AddFeedback(ctx context.Context, req *AddFeedbackRequest) (*AddFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFeedback not implemented")
}
func (*UnimplementedCustomerFeedbackServer) GetFeedbackByPassengerID(ctx context.Context, req *GetFeedbackByPassengerIDRequest) (*GetFeedbackByPassengerIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackByPassengerID not implemented")
}
func (*UnimplementedCustomerFeedbackServer) GetFeedbackByBookingCode(ctx context.Context, req *GetFeedbackByBookingCodeRequest) (*GetFeedbackByBookingCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackByBookingCode not implemented")
}

func RegisterCustomerFeedbackServer(s *grpc.Server, srv CustomerFeedbackServer) {
	s.RegisterService(&_CustomerFeedback_serviceDesc, srv)
}

func _CustomerFeedback_AddFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerFeedbackServer).AddFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomerFeedback.CustomerFeedback/AddFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerFeedbackServer).AddFeedback(ctx, req.(*AddFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerFeedback_GetFeedbackByPassengerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackByPassengerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerFeedbackServer).GetFeedbackByPassengerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomerFeedback.CustomerFeedback/GetFeedbackByPassengerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerFeedbackServer).GetFeedbackByPassengerID(ctx, req.(*GetFeedbackByPassengerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerFeedback_GetFeedbackByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackByBookingCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerFeedbackServer).GetFeedbackByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomerFeedback.CustomerFeedback/GetFeedbackByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerFeedbackServer).GetFeedbackByBookingCode(ctx, req.(*GetFeedbackByBookingCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerFeedback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CustomerFeedback.CustomerFeedback",
	HandlerType: (*CustomerFeedbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFeedback",
			Handler:    _CustomerFeedback_AddFeedback_Handler,
		},
		{
			MethodName: "GetFeedbackByPassengerID",
			Handler:    _CustomerFeedback_GetFeedbackByPassengerID_Handler,
		},
		{
			MethodName: "GetFeedbackByBookingCode",
			Handler:    _CustomerFeedback_GetFeedbackByBookingCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CustomerFeedback.proto",
}
